#!/bin/sh -x

# TestSuite General Variables
export ACCELEROMETER_POSTFIX=`date "+%Y%m%d-%H%M%S"`
export ACCELEROMETER_ROOT=`pwd`

export ACCELEROMETER_DIR_BINARIES=${ACCELEROMETER_ROOT}/../bin
export ACCELEROMETER_DIR_HELPER=${ACCELEROMETER_ROOT}/helper
export ACCELEROMETER_DIR_TMP=${ACCELEROMETER_ROOT}/tmp
export ACCELEROMETER_DIR_TEST=${ACCELEROMETER_ROOT}/test
export ACCELEROMETER_DIR_SCENARIOS="${ACCELEROMETER_ROOT}/scenarios"

export ACCELEROMETER_FILE_OUTPUT=${ACCELEROMETER_ROOT}/output.$ACCELEROMETER_POSTFIX
export ACCELEROMETER_FILE_LOG=${ACCELEROMETER_ROOT}/log.$ACCELEROMETER_POSTFIX
export ACCELEROMETER_FILE_TMP=${ACCELEROMETER_DIR_TMP}/tmp.$ACCELEROMETER_POSTFIX
export ACCELEROMETER_FILE_CMD=cmd.$ACCELEROMETER_POSTFIX

export ACCELEROMETER_DURATION=""
export ACCELEROMETER_PRETTY_PRT=""
export ACCELEROMETER_VERBOSE=""
export ACCELEROMETER_SCENARIO_NAMES=""
export ACCELEROMETER_STRESS=""

export PATH="${PATH}:${ACCELEROMETER_ROOT}:${ACCELEROMETER_DIR_BINARIES}:${ACCELEROMETER_DIR_HELPER}"

# Utils General Variables
export UTILS_DIR=$ACCELEROMETER_ROOT/../../utils/
export UTILS_DIR_BIN=$UTILS_DIR/bin
export UTILS_DIR_HANDLERS=$UTILS_DIR/handlers
export UTILS_DIR_SCRIPTS=$UTILS_DIR/scripts

export PATH="$PATH:$UTILS_DIR_BIN:$UTILS_DIR_HANDLERS:$UTILS_DIR_SCRIPTS"

. $UTILS_DIR/configuration/general.configuration
if [ `cat $SYSFS_BOARD_REV | grep -c "Tablet"` -ge 1 ]; then
	# Specific to bma180 sensor
	export ACCELEROMETER_SYSFS_PATH="/sys/bus/i2c/drivers/bma180_accel/4-0040"
	export ACCELEROMETER_HW="bma180"
	export ACCELEROMETER_POWERON_VAL=1
	export ACCELEROMETER_POWEROFF_VAL=0
	export ACCELEROMETER_ENABLE_POWER="$ACCELEROMETER_SYSFS_PATH/enable"
elif [ `cat $SYSFS_BOARD_REV | grep -wc "Blaze/SDP"` -ge 1  ]; then
	# Specific to cma3000 sensor
	export ACCELEROMETER_MODE_MEAS400=2
	export ACCELEROMETER_MODE_MEAS40=3
	export ACCELEROMETER_MODE_MOTDET=4
	export ACCELEROMETER_MODE_FF_100=5
	export ACCELEROMETER_MODE_FF_400=6
	export ACCELEROMETER_MODE_OFF_7=7
	export ACCELEROMETER_RANGE_2G=2000
	export ACCELEROMETER_RANGE_8G=8000

	export ACCELEROMETER_SYSFS_PATH="/sys/bus/i2c/drivers/cma3000_accl/4-001c"
	export ACCELEROMETER_HW="cma3000"
	export ACCELEROMETER_POWERON_VAL=3
	export ACCELEROMETER_POWEROFF_VAL=0
	export ACCELEROMETER_ENABLE_POWER="$ACCELEROMETER_SYSFS_PATH/power_state"
elif [ `cat /proc/cpuinfo| grep -ic OMAP5` -ne 0 ];then
	export ACCELEROMETER_SYSFS_PATH="/sys/bus/i2c/drivers/mpu6050/2-0068"
	export ACCELEROMETER_HW="mpu6050"
	export ACCELEROMETER_POWERON_VAL=1
	export ACCELEROMETER_POWEROFF_VAL=0
	export ACCELEROMETER_ENABLE_POWER="$ACCELEROMETER_SYSFS_PATH/accel_enable"
else
	echo "Warning: Unrecognized hardware platform"
	exit 1
fi
export ACCELEROMETER_MODE_OFF_0=0
export ACCELEROMETER_MODE_MEAS100=1


# General variables
export DMESG_FILE=/var/log/dmesg

$UTILS_DIR_SCRIPTS/mknodins.sh

# Sensor devfs node
TEMP_EVENT=`ls /sys/class/input/ | grep event`
set $TEMP_EVENT

for i in $TEMP_EVENT
do
	cat /sys/class/input/$i/device/name | grep "$ACCELEROMETER_HW"
	IS_THIS_OUR_DRIVER=`echo $?`
	if [ "$IS_THIS_OUR_DRIVER" -eq "0" ]
	then
		export DEVFS_ACCELEROMETER=/dev/input/$i
		echo "Accelerometer node is " $DEVFS_ACCELEROMETER
	fi
done

if [ ! -e "$DEVFS_ACCELEROMETER" ]
then
	echo "FATAL: Accelerometer node cannot be found -> $DEVFS_ACCELEROMETER"
	exit 1
fi

# End of file
